---
# 开发环境的参数
server:
  port: 8080
# 定义开发环境
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
      additional-exclude: src/main/java
      exclude: WEB-INF/
      poll-interval: 200ms
      quiet-period: 100ms

---
# 测试环境的参数
server:
  port: 8081

# 定义测试环境
spring:
  config:
    activate:
      on-profile: test
  devtools:
    livereload:
      enabled: true
---
# 生产环境的参数
server:
  port: 8082

# 定义生产环境
spring:
  config:
    activate:
      on-profile: pro
  devtools:
    livereload:
      enabled: false
---
# 配置使用哪个环境的参数
spring:
  profiles:
    active: dev