server:
  port: 8080

spring:
  application:
    name: livehelper

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true
      additional-exclude: src/main/java
      exclude: WEB-INF/
      poll-interval: 20ms
      quiet-period: 10ms
      log-condition-evaluation-delta: false

  banner:
    charset: utf-8
    location: classpath:banner.txt

  datasource:
    url: jdbc:mysql://localhost:3306/livehelper?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

logging:
  config: classpath:logback.xml
  level:
    root: info

# mybatis:
#   mapper-locations:
#     - classpath:mapper/**/*.xml
#   type-aliases-package: top.caoayu.livehelper.entity
#   configuration:
#     cache-enabled: true
#     use-generated-keys: true
#     default-executor-type: REUSE
#     use-actual-param-name: true
